markdown_extensions:
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

  - toc:
      permalink: true
      toc_depth: 3

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
site_name: KosmoS Lab
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  #custom_dir: custom
  font:
    text: Source Code Pro
    code: Source Code Pro Mono
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

    #- navigation.instant
    #- navigation.sections
    #- navigation.tabs
    # - navigation.top

    #- navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  plugins:
    - privacy
  language: en

repo_url: https://github.com/kosmos-lab/kosmos-platform/
repo_name: kosmos-platform
edit_uri: ""

extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Features:
      - features/index.md
      - KREE: features/kree.md
      - Access-Control: features/access-control.md
      - Cameras: features/cameras.md
      - JSON-Schema: features/json-schema.md
      - Live-Annotation: features/live-annotation.md
      - Plugins: features/plugins.md
      - Smart-Environment: features/smart-environment.md
      - Wizard-of-Oz: features/wizard-of-oz.md
  - Installation:
      - install/index.md

  - Configuration:
      - config/index.md

  - Usage:
      - usage/index.md

  - Plugins: plugins/index.md
